server:
  port: 8888

app:
  httpPrefix: /api/v1
  services:
    identity: http://localhost:8080/identity

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.httpPrefix}/identity/**
          filters:
            - StripPrefix=2

        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.httpPrefix}/profile/**
          filters:
            - StripPrefix=2