server:
  port: 8081
  servlet:
    contextPath: /profile
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

  jwt:
    signerKey: "atV35tiPqJgeGT8/eoSFNclzD+jIZKoKFA8REJFOWWc0tr82qrSNSizslEz5qnGG"