server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    signerKey: "atV35tiPqJgeGT8/eoSFNclzD+jIZKoKFA8REJFOWWc0tr82qrSNSizslEz5qnGG"

app:
  services:
   profile: http://localhost:8081/profile
